name = "chatter"
main = "build/worker/shim.mjs"
compatibility_date = "2024-07-31"

[build]
command = "cargo install -q worker-build && worker-build --release"

[durable_objects]
bindings = [{ name = "CHATROOM", class_name = "Chatroom" }]

